[package]
name = "ckks-piop"
version = "0.1.0"
edition = "2021"

[dependencies]
concrete-ntt = { version = "0.2", features = ["nightly"] }
rug = "1.22.0"
rand = "*"
sha3 = "0.10"
modinverse = "0.1.1"
